Creates iMessage extension for the main app
lauyoo46/iOSIntermediate pull request #30
Opened 2021-01-28 13:09 UTC by lauyoo46

<img width="379" alt="Screenshot 2021-01-28 at 14 49 39" src="https://user-images.githubusercontent.com/38860865/106141768-4f0b2680-6179-11eb-8991-400bd22ab256.png">
<img width="379" alt="Screenshot 2021-01-28 at 14 49 55" src="https://user-images.githubusercontent.com/38860865/106141773-503c5380-6179-11eb-8f4f-82e4040f9c39.png">

2021-01-29 15:27 UTC, czegreanu requested changes

2021-01-29 15:27 UTC, czegreanu commented on CollectionViewDemo/IconDetailViewController.swift
> +            descriptionLabel.numberOfLines = 0
this should be in storyboard

2021-01-29 15:27 UTC, czegreanu commented on IconDataKit/Icon.swift
> +        guard let messageURL = message?.url else {
concatenate this 2 guards in only one

2021-01-29 15:27 UTC, czegreanu commented on IconDataKit/Icon.swift
> +
:(

2021-01-29 15:27 UTC, czegreanu commented on IconStore/IconTableViewCell.swift
> +            descriptionLabel.numberOfLines = 0
same here, move to storyboard

2021-01-29 15:31 UTC, czegreanu commented on CollectionViewDemo/IconDetailViewController.swift
> +    @IBOutlet var descriptionLabel: UILabel! {
please leave a space between the fields if they have didSet. it is easier to read

2021-02-01 07:57 UTC, a-nistor approved these changes

2021-02-01 09:44 UTC, czegreanu approved these changes

2021-02-01 13:03 UTC, merged