Integrates Firebase services into the app
lauyoo46/iOSIntermediate pull request #32
Opened 2021-01-29 11:10 UTC by lauyoo46

Functionalities implemented: 
1. SignUp with email verification
2. Login
3. Logout
4. Forgot password

<img width="379" alt="Screenshot 2021-01-29 at 12 50 02" src="https://user-images.githubusercontent.com/38860865/106268042-352e1a00-6233-11eb-891d-7def45c5fed9.png">
<img width="379" alt="Screenshot 2021-01-29 at 12 51 43" src="https://user-images.githubusercontent.com/38860865/106268052-38290a80-6233-11eb-8850-326509ba5845.png">
<img width="379" alt="Screenshot 2021-01-29 at 12 52 14" src="https://user-images.githubusercontent.com/38860865/106268060-3b23fb00-6233-11eb-8bf8-e2114c4d5268.png">
<img width="379" alt="Screenshot 2021-01-29 at 12 52 44" src="https://user-images.githubusercontent.com/38860865/106268072-3e1eeb80-6233-11eb-9f01-0879875586ae.png">
<img width="379" alt="Screenshot 2021-01-29 at 12 52 51" src="https://user-images.githubusercontent.com/38860865/106268081-41b27280-6233-11eb-9702-83e1e2df10a2.png">
<img width="379" alt="Screenshot 2021-01-29 at 12 53 25" src="https://user-images.githubusercontent.com/38860865/106268090-4545f980-6233-11eb-9f57-fd15c43b3cce.png">

2021-01-29 15:53 UTC, czegreanu requested changes

2021-01-29 15:53 UTC, czegreanu commented on FirebaseDemo/LoginViewController.swift
> +    override func viewWillDisappear(_ animated: Bool) {
you can delete this, wrong and not needed :)

2021-02-01 08:00 UTC, a-nistor approved these changes

2021-02-01 09:45 UTC, czegreanu approved these changes

2021-02-01 13:04 UTC, merged