Creates real-time image recognition app
lauyoo46/iOSIntermediate pull request #35
Opened 2021-02-02 15:50 UTC by lauyoo46

2021-02-03 07:45 UTC, czegreanu requested changes

2021-02-03 07:45 UTC, czegreanu commented on ImageRecognition/CameraController.swift
> +        captureSession.startRunning()
call super method

2021-02-03 07:45 UTC, czegreanu commented on ImageRecognition/CameraController.swift
> +        captureSession.stopRunning()
same here

2021-02-04 07:31 UTC, czegreanu approved these changes

2021-02-16 13:01 UTC, a-nistor approved these changes

2021-02-16 13:51 UTC, merged